name: Node CI

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install and test
      run: |
        cd demo
        yarn
        cd ..
        yarn
        yarn test
      env:
        CI: true

  elm-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: validate with elm-format
      run: |
        cd demo
        yarn
        yarn build
        yarn check-format

  build-demo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install module dependencies
      run: yarn install --frozen-lockfile --production
    - name: Check demo site builds
      working-directory: demo
      run: |
        yarn install --frozen-lockfile --production
        yarn run build-prod
